/* eslint-disable react/no-children-prop */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "../redux/provider";
import {cn} from "../lib/utils";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}:{
  children: React.ReactNode;
}) {
  return (
    <Providers>
    <html lang="en">
      <body className={cn('min-h-screen font-sans antialiased grainy',inter.className)}>
        <Navbar />
        {children}
        </body>
        
    </html>
    </Providers>
  );
}
